modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="bilingualtooltips"
version="${file.jarVersion}"
displayName="Bilingual Tooltips"
authors="PageQwQ"
description='''
Shows an item's name in a second language in its tooltip (e.g. Chinese and English).
'''

[[dependencies.bilingualtooltips]]
modId="neoforge"
type="required"
versionRange="[26.2.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.bilingualtooltips]]
modId="minecraft"
type="required"
versionRange="[26.2]"
ordering="NONE"
side="BOTH"

[[dependencies.bilingualtooltips]]
modId="cloth_config"
type="required"
versionRange="[26.2.155,)"
ordering="NONE"
side="BOTH"
